apiVersion: v1
kind: Secret
metadata:
  name: mqtt
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ= #echo -n 'password' | base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s2mqtt
  name: k8s2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s2mqtt
  template:
    metadata:
      labels:
        app: k8s2mqtt
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Rome
            - name: HOST
              value: "mosquitto.mosquitto.svc.cluster.local"
            - name: KUBECONFIG
              value: /kube/kubeconfig
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt
                  key: password

            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt
                  key: username
            - name: PORT
              value: "1883"
          image: william1608/k8s2mqtt:2.4.2
          imagePullPolicy: IfNotPresent
          name: k8s2mqtt
          livenessProbe:
            exec:
              command:
                - cat
                - /etc/os-release
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - mountPath: /kube/kubeconfig
              name: config
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
      restartPolicy: Always
      volumes:
        - name: config
          nfs: #you can use hostpath or other method
            server: ip server
            path: /path to/kubeconfig
