apiVersion: v1
kind: Secret
metadata:  
  name: mqtt
type: Opaque
data:
  host: aG9zdA==  #echo -n 'host' | base64
  username: dXNlcm5hbWU=  
  password: cGFzc3dvcmQ=
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s2mqtt
  name: k8s2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s2mqtt
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Rome
            - name: HOST
              valueFrom: 
                secretKeyRef: 
                  name: mqtt 
                  key: host 
            - name: KUBECONFIG
              value: /kube/config
            - name: PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: mqtt 
                  key: password
            
            - name: USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: mqtt 
                  key: username
            - name: PORT
              value: 1883
          image: william1608/k8s2mqtt:2.4.0
          imagePullPolicy: IfNotPresent
          name: k8s2mqtt
          livenessProbe:
            exec:
              command:
              - cat
              - /etc/os-release
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /kube/config
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            path: ~/.kube/config
